# Generated by Django 5.2.4 on 2025-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('order_created', 'Commande créée'), ('order_confirmed', 'Commande confirmée'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('stock_updated', 'Stock mis à jour'), ('product_added', 'Produit ajouté'), ('product_updated', 'Produit modifié'), ('receipt_generated', 'Reçu généré'), ('agent_created', 'Agent créé'), ('agent_updated', 'Agent modifié')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('supervisor', 'Superviseur'), ('manager', 'Manager'), ('admin', 'Administrateur')], default='agent', max_length=20, verbose_name='Rôle'),
        ),
    ]
