# Generated by Django 5.1.4 on 2025-08-03 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stock_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format: +235 XX XX XX XX ou 66XXXXXX', regex='^(?:\\+235\\s?)?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
