# Generated by Django 5.1.4 on 2025-08-03 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format accepté : +235 XX XX XX XX ou XX XX XX XX (8 chiffres)', regex='^(\\+235\\s?)?(6[0-9]{1})(\\s?[0-9]{2}){3}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
