# Generated by Django 5.1.4 on 2025-08-03 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format accepté : +235 XX XX XX XX, XX XX XX XX ou XXXXXXXX (8 chiffres commençant par 6)', regex='^(\\+235[\\s-]?)?(6\\d[\\s-]?)(\\d{2}[\\s-]?){2}\\d{2}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
