# Generated by Django 5.1.4 on 2025-08-03 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Le numéro doit contenir au moins 8 chiffres')], verbose_name='Numéro de téléphone'),
        ),
    ]
