# Generated by Django 5.1.4 on 2025-08-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_number'], name='orders_clie_phone_n_97393c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='orders_clie_last_na_6ee1ce_idx'),
        ),
    ]
