# Generated by Django 5.1.4 on 2025-08-04 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='orders_clie_phone_n_97393c_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='orders_clie_last_na_6ee1ce_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Le numéro doit contenir au moins 8 chiffres')], verbose_name='Numéro de téléphone'),
        ),
    ]
