# Generated by Django 5.1.4 on 2025-08-04 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_client_orders_clie_phone_n_97393c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Entrez un numéro valide au format : +235 XX XX XX XX ou 66 XX XX XX', regex='^(\\+235\\s?)?\\d{2}(\\s?\\d{2}){3}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
