# Generated by Django 5.1.4 on 2025-08-04 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Entrez un numéro valide au format : +235 XX XX XX XX, 00235 XX XX XX XX, 235 XX XX XX XX ou XX XX XX XX (doit commencer par 6,7,8 ou 9)', regex='^(\\+235|00235|235)?[6789]\\d{1}(\\s?\\d{2}){3}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
